version: "3"

services:

    db:
        image: mysql:8.0.25
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bonsai_db
        ports:
            - 3306:3306

    web:
        build: .
        environment:
            - env=docker
        command: bash -c "ls && chmod 775 wait.sh app && sh wait.sh"
        volumes:
            - .:/back_end
        ports:
            - 8000:8000
        depends_on:
            - db